name: packages/common
on:
  push:
    paths:
      - 'src/common/**'
      - '.github/workflows/common.yml'
  pull_request:
    paths:
      - 'src/common/**'
      - '.github/workflows/common.yml'

jobs:
  build-lint-test:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        working-directory: 'src/common'
        env:
          CI: true
        run: npm ci

      - name: Build
        working-directory: 'src/common'
        run: npm run build

      - name: Lint
        working-directory: 'src/common'
        run: npm run lint # -- --max-warnings -1

      - name: Test
        working-directory: 'src/common'
        run: npm test
