name: packages/common
on:
  push:
    paths:
      - 'src/common/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/common.yml'
  pull_request:
    paths:
      - 'src/common/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/common.yml'
env:
  node-version: 15

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        run: npm ci

      - name: Build
        run: npm run build -w @tezospayments/common

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [14, 15, 16]
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        run: npm ci

      - name: Test
        run: npm test -w @tezospayments/common

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        run: npm ci

      - name: Lint
        run: npm run lint -w @tezospayments/common # -- --max-warnings -1
