name: apps/docs
on:
  push:
    paths:
      - 'apps/docs/**'
      - '.github/workflows/docs-app.yml'
    branches:
      - master
      - dev
  pull_request:
    paths:
      - 'apps/docs/**'
      - '.github/workflows/docs-app.yml'
      - 'scripts/netlify-pr-notifications.js'
env:
  node-version: 16

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: 'apps/docs/package-lock.json'

      - name: Update npm if needed
        if: ${{ env.node-version < 15 }}
        run: npm install -g npm@latest

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        working-directory: apps/docs
        run: npm ci

      - name: Build the Docs app
        working-directory: apps/docs
        run: npm run build

      - name: Upload the Docs app build as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: apps/docs/build
          retention-days: 10

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Download the Docs app build from the artifacts storage
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: apps/docs/build

      - name: Push to the ${{ env.publish-branch }} branch
        env:
          publish-branch: build
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/docs/build
          destination_dir: apps/docs
          exclude_assets: '**/*.LICENSE,**/*.LICENSE.txt'
          publish_branch: ${{ env.publish-branch }}

  deploy-preview:
    name: Deploy the preview
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Download the Docs app build from the artifacts storage
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: apps/docs/build

      - name: Print environment info
        run: netlify version

      - name: Create the "_redirects" file
        run: echo "/*   /index.html   200" > apps/docs/build/_redirects

      - name: Deploy to Netlify
        id: netlify_deployment
        env:
          NETLIFY_SITE_ID: ${{ secrets.DOCS_APP_NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.TEZOS_PAYMENTS_DEVELOPMENT_NETLIFY_ACCESS_TOKEN }}
        run: |
          netlify_deploy_result="$(netlify deploy \
            --dir=apps/docs/build \
            --alias='dev${{ github.event.pull_request.number }}' \
            --message='${{ github.event.pull_request.title }}' \
            --json \
          )"
          # Multiline to single line
          netlify_deploy_result="${netlify_deploy_result//$'\n'/' '}"

          echo "::set-output name=netlify_deploy_result::$netlify_deploy_result"

      - name: Send a notification to the related pull request, PR#${{ github.event.pull_request.number }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/netlify-pr-notifications.js')
            await script({ 
              github, 
              context,
              commitSha: '${{ github.event.pull_request.head.sha }}',
              currentAppName: 'Docs',
              netlifyDeployResult: ${{ steps.netlify_deployment.outputs.netlify_deploy_result }}
            })
