name: apps/landing
on:
  push:
    paths:
      - 'apps/landing/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/landing-app.yml'
    branches:
      - master
      - dev
  pull_request:
    paths:
      - 'apps/landing/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/landing.yml'
env:
  node-version: 16

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update npm if needed
        if: ${{ env.node-version < 15 }}
        run: npm install -g npm@latest

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Define required environment vars
        run: echo "REACT_APP_COMMIT_SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install npm packages
        run: npm ci

      - name: Build the Landing app
        run: npm run build -w @tezospayments/landing

      - name: Upload the Landing app build as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: landing
          path: apps/landing/dist
          retention-days: 10

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Download the Landing app build from the artifacts storage
        uses: actions/download-artifact@v2
        with:
          name: landing
          path: apps/landing/dist

      - name: Push to the ${{ env.publish-branch }} branch
        env:
          publish-branch: dist
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/landing/dist
          destination_dir: apps/landing
          exclude_assets: '**/*.LICENSE,**/*.LICENSE.txt'
          publish_branch: ${{ env.publish-branch }}
