name: apps/payment-react-web
on:
  push:
    paths:
      - 'src/common/**'
      - 'src/payment-react-web/**'
      - '.github/workflows/payment-react-web.yml'
  pull_request:
    paths:
      - 'src/common/**'
      - 'src/payment-react-web/**'
      - '.github/workflows/payment-react-web.yml'

jobs:
  build-lint-deploy:
    name: Build, Lint and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15'

      - name: Define required environment vars
        run: echo "REACT_APP_COMMIT_SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        working-directory: 'src/common'
        env:
          CI: true
        run: npm ci -w @tezospayments/common -w @tezospayments/payment-react-web

      - name: Build the @tezospayments/common package
        run: npm run build -w @tezospayments/common

      - name: Build the payment app
        run: npm run build -w @tezospayments/payment-react-web

      - name: Lint the payment app
        run: npm run lint -w @tezospayments/payment-react-web # -- --max-warnings -1

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'src/payment-react-web/build'
          exclude_assets: '**/*.LICENSE,**/*.LICENSE.txt'
          publish_branch: dist/payment-react-web
