name: apps/payment-react-web
on:
  push:
    paths:
      - 'packages/js/common/**'
      - 'packages/js/react-web-core/**'
      - 'apps/payment-react-web/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/payment-react-web-app.yml'
    branches:
      - master
      - dev
  pull_request:
    paths:
      - 'packages/js/common/**'
      - 'packages/js/react-web-core/**'
      - 'apps/payment-react-web/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/payment-react-web-app.yml'
      - 'scripts/netlify-pr-notifications.js'
env:
  node-version: 16

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update npm if needed
        if: ${{ env.node-version < 15 }}
        run: npm install -g npm@latest

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Define required environment vars
        run: echo "REACT_APP_COMMIT_SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install npm packages
        run: npm ci

      - name: Build the @tezospayments/common package
        run: npm run build -w @tezospayments/common

      - name: Build the @tezospayments/react-web-core package
        run: npm run build -w @tezospayments/react-web-core

      - name: Build the Payment app
        run: npm run build -w @tezospayments/payment-react-web

      - name: Upload the Payment app build as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: payment-react-web
          path: apps/payment-react-web/build
          retention-days: 10

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update npm if needed
        if: ${{ env.node-version < 15 }}
        run: npm install -g npm@latest

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        run: npm ci

      - name: Lint
        run: npm run lint -w @tezospayments/payment-react-web # -- --max-warnings -1

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Download the Payment app build from the artifacts storage
        uses: actions/download-artifact@v2
        with:
          name: payment-react-web
          path: apps/payment-react-web/build

      - name: Push to the ${{ env.publish-branch }} branch
        env:
          publish-branch: dist
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/payment-react-web/build
          destination_dir: apps/payment-react-web
          exclude_assets: '**/*.LICENSE,**/*.LICENSE.txt'
          publish_branch: ${{ env.publish-branch }}

  deploy-preview:
    name: Deploy the preview
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: github.event_name == 'pull_request'
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Download the Payment app build from the artifacts storage
        uses: actions/download-artifact@v2
        with:
          name: payment-react-web
          path: apps/payment-react-web/build

      - name: Print environment info
        run: netlify version

      - name: Create the "_redirects" file
        run: echo "/*   /index.html   200" > apps/payment-react-web/build/_redirects

      - name: Create the robots.txt file
        run: |
          rm apps/payment-react-web/build/robots.txt
          echo "User-agent: *" > apps/payment-react-web/build/robots.txt
          echo "Disallow: /" > apps/payment-react-web/build/robots.txt

      - name: Deploy to Netlify
        id: netlify_deployment
        env:
          NETLIFY_SITE_ID: ${{ secrets.PAYMENT_APP_NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.TEZOS_PAYMENTS_DEVELOPMENT_NETLIFY_ACCESS_TOKEN }}
        run: |
          netlify_deploy_result="$(netlify deploy \
            --dir=apps/payment-react-web/build \
            --alias='dev${{ github.event.pull_request.number }}' \
            --message='${{ github.event.pull_request.title }}' \
            --json \
          )"
          # Multiline to single line
          netlify_deploy_result="${netlify_deploy_result//$'\n'/' '}"

          echo "::set-output name=netlify_deploy_result::$netlify_deploy_result"

      - name: Send a notification to the related pull request, PR#${{ github.event.pull_request.number }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/netlify-pr-notifications.js')
            await script({ 
              github, 
              context,
              commitSha: '${{ github.event.pull_request.head.sha }}',
              currentAppName: 'Payment', 
              netlifyDeployResult: ${{ steps.netlify_deployment.outputs.netlify_deploy_result }}
            })

  