name: packages/js/tezospayments
on:
  push:
    paths:
      - 'packages/js/common/**'
      - 'packages/js/tezospayments/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/tezospayments-js-package.yml'
    branches:
      - master
      - dev
    tags:
      - 'js/tezospayments@*.*.*'
      - 'js/tezospayments@*.*.*-*'
  pull_request:
    paths:
      - 'packages/js/common/**'
      - 'packages/js/tezospayments/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/tezospayments-js-package.yml'
env:
  node-version: 16

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Update npm if needed
        if: ${{ env.node-version < 15 }}
        run: npm install -g npm@latest

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        run: npm ci

      - name: Build the @tezospayments/common package
        run: npm run build -w @tezospayments/common

      - name: Build the tezospayments package
        run: npm run build -w tezospayments

      - name: Upload the build as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: tezospayments
          path: |
            packages/js/tezospayments/dist
            packages/js/tezospayments/package.json
            packages/js/tezospayments/README.md
            packages/js/tezospayments/LICENSE
          retention-days: 10

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [14, 16]
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Update npm if needed
        if: ${{ matrix.node-version < 15 }}
        run: npm install -g npm@latest

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        run: npm ci

      - name: Build the @tezospayments/common package
        run: npm run build -w @tezospayments/common

      - name: Test
        run: npm test -w tezospayments

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Update npm if needed
        if: ${{ env.node-version < 15 }}
        run: npm install -g npm@latest

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        run: npm ci

      - name: Lint
        run: npm run lint -w tezospayments # -- --max-warnings -1

  release:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    if: ${{ contains(github.ref, 'refs/tags/js/tezospayments@') }}
    steps:
      - name: Download the build from the artifacts storage
        uses: actions/download-artifact@v2
        with:
          name: tezospayments

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ env.node-version }}

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push to the ${{ env.publish-branch }} branch
        env:
          publish-branch: dist
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './'
          destination_dir: packages/js/tezospayments
          publish_branch: ${{ env.publish-branch }}
