name: packages/tezospayments [npm]
on:
  push:
    paths:
      - 'src/common/**'
      - 'src/tezospayments/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/npm-tezospayments.yml'
    branches:
      - master
      - dev
    tags:
      - 'npm/tezospayments@*.*.*'
      - 'npm/tezospayments@*.*.*-*'
  pull_request:
    paths:
      - 'src/common/**'
      - 'src/tezospayments/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/npm-tezospayments.yml'
env:
  node-version: 15

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update npm if needed
        if: ${{ env.node-version < 15 }}
        run: npm install -g npm@latest

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Install npm packages
        run: npm ci

      - name: Build the @tezospayments/common package
        run: npm run build -w @tezospayments/common

      - name: Build the tezospayments package
        run: npm run build -w tezospayments

      - name: Upload the build as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: tezospayments
          path: |
            src/tezospayments/dist
            src/tezospayments/package.json
            src/tezospayments/README.md
            src/tezospayments/LICENSE
          retention-days: 10

  release:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ contains(github.ref, 'refs/tags/npm/tezospayments@') }}
    steps:
      - name: Download the build from the artifacts storage
        uses: actions/download-artifact@v2
        with:
          name: tezospayments

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ env.node-version }}

      - name: Print environment info
        run: |
          node --version
          npm --version

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push to the ${{ env.publish-branch }} branch
        env:
          publish-branch: dist
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './'
          destination_dir: packages/npm/tezospayments
          publish_branch: ${{ env.publish-branch }}
