name: packages/dotnet/tezospayments
on:
  push:
    paths:
      - 'packages/dotnet/TezosPayments/**'
      - 'packages/dotnet/TezosPayments.*/**'
      - '.github/workflows/tezospayments-dotnet-package.yml'
    branches:
      - master
      - dev
    tags:
      - 'dotnet/TezosPayments.*.*.*'
      - 'dotnet/TezosPayments.*.*.*-*'
  pull_request:
    paths:
      - 'packages/dotnet/TezosPayments/**'
      - 'packages/dotnet/TezosPayments.*/**'
      - '.github/workflows/tezospayments-dotnet-package.yml'
env:
  dotnet-version: '6.0.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up .NET ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: Print environment info
        run: |
          dotnet --info

      - name: Install dependencies
        working-directory: packages/dotnet/TezosPayments
        run: dotnet restore

      - name: Build the TezosPayments package
        working-directory: packages/dotnet/TezosPayments
        run: dotnet build -c Release

      - name: Pack the TezosPayments package into a NuGet package
        working-directory: packages/dotnet/TezosPayments
        run: dotnet pack --no-build -c Release -o nuget-package
        env:
          TEZOS_PAYMENTS_COMMIT_SHA: ${{ github.sha }}

      - name: Upload the build and nuget package as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: tezospayments-dotnet-package
          path: |
            packages/dotnet/TezosPayments/bin
            packages/dotnet/TezosPayments/nuget-package
          retention-days: 10

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Set up .NET ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: Print environment info
        run: |
          dotnet --info

      - name: Install dependencies
        working-directory: packages/dotnet/TezosPayments.Tests
        run: dotnet restore

      - name: Test
        working-directory: packages/dotnet/TezosPayments.Tests
        run: dotnet test -l "console;verbosity=normal"

  release:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    needs: [build, test]
    if: ${{ contains(github.ref, 'refs/tags/dotnet/TezosPayments_') }}
    steps:
      - name: Download the nuget package from the artifacts storage
        uses: actions/download-artifact@v2
        with:
          name: tezospayments-dotnet-package

      - name: Set up .NET ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/fastwaterbear/index.json
          dotnet-version: ${{ env.dotnet-version }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

      - name: Print environment info
        run: |
          dotnet --info

      - name: Publish
        working-directory: nuget-package
        run: dotnet nuget push *.nupkg

      - name: Push to the ${{ env.publish-branch }} branch
        env:
          publish-branch: dist
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305 # v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './'
          destination_dir: packages/dotnet/TezosPayments
          publish_branch: ${{ env.publish-branch }}
